"""Deployed plant-disease taxonomy shared by inference and dataset tooling."""

# Recovered from the companion PlantVillage project. The order matches the
# trained model's 39 outputs; index 4 is the non-leaf background class.

CLASS_NAMES = [
    "Apple Apple scab",
    "Apple Black rot",
    "Apple Cedar apple rust",
    "Apple healthy",
    "Background without leaves",
    "Blueberry healthy",
    "Cherry Powdery mildew",
    "Cherry healthy",
    "Corn Cercospora leaf spot",
    "Corn Common rust",
    "Corn Northern Leaf Blight",
    "Corn healthy",
    "Grape Black rot",
    "Grape Esca",
    "Grape Leaf blight",
    "Grape healthy",
    "Orange Huanglongbing",
    "Peach Bacterial spot",
    "Peach healthy",
    "Bell pepper Bacterial spot",
    "Bell pepper healthy",
    "Potato Early blight",
    "Potato Late blight",
    "Potato healthy",
    "Raspberry healthy",
    "Soybean healthy",
    "Squash Powdery mildew",
    "Strawberry Leaf scorch",
    "Strawberry healthy",
    "Tomato Bacterial spot",
    "Tomato Early blight",
    "Tomato Late blight",
    "Tomato Leaf Mold",
    "Tomato Septoria leaf spot",
    "Tomato Spider mites",
    "Tomato Target Spot",
    "Tomato Yellow Leaf Curl Virus",
    "Tomato mosaic virus",
    "Tomato healthy",
]
